<a href="https://colab.research.google.com/github/namvv17/ThuchanhToanCC/blob/main/th%E1%BB%B1c_h%C3%A0nh_ch%C6%B0%C6%A1ng_2d%C3%A1iotuyentinh.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from numpy import *
vec1 = np.array([1., 3., 5.])
print(vec1 * 2) 

[ 2.  6. 10.]


In [3]:
 print(vec1 /2) 

[0.5 1.5 2.5]


In [4]:
print(vec1 + vec1)

[ 2.  6. 10.]


In [9]:
vec2 = array([2., 4., 0])
print(vec1 + vec2)

[3. 7. 5.]


In [12]:
vec3 = array([2., 4., 6.])
print(vec1 + vec3)

[ 3.  7. 11.]


In [13]:
print(vec1 / vec3) 

[0.5        0.75       0.83333333]


In [14]:
print(vec1 * vec3)

[ 2. 12. 30.]


In [16]:
print(2* vec1 + 5* vec3)

[12. 26. 40.]


Chương 2:: MA TRẬN VÀ HỆ PHƯƠNG TRÌNH TUYẾN
TÍNH 
1.Dẫn nhập – Một số hàm về xử lý vector với Python **bold text**

**Bài 2**

In [38]:
import numpy as np
from scipy import linalg, sparse
D = np.mat([ [3,4], [5,6] ])
print(D)

[[3 4]
 [5 6]]


In [42]:
C = np.mat(np.random.random((5,7)))
print(C) 

[[0.53790545 0.4208509  0.89538585 0.10449986 0.38491056 0.28822314
  0.13484896]
 [0.87122967 0.69835667 0.51171964 0.30379446 0.38428541 0.35228193
  0.96240575]
 [0.49701034 0.0538976  0.61154165 0.27423072 0.95134594 0.76590974
  0.36297638]
 [0.68621952 0.83942045 0.23058339 0.56242748 0.50101478 0.17039963
  0.06785816]
 [0.37725102 0.5489545  0.46039273 0.06179668 0.72137937 0.54699835
  0.38676871]]


In [43]:
A =np.mat(np.random.random((2,2)))
print(A) 

[[0.72449333 0.13697844]
 [0.0629135  0.93928217]]


In [46]:
b = np.array([(1+5j, 2j, 3j),(4, 5,6)])
B = np.asmatrix(b)
print(b)
print(B) 

[[1.+5.j 0.+2.j 0.+3.j]
 [4.+0.j 5.+0.j 6.+0.j]]
[[1.+5.j 0.+2.j 0.+3.j]
 [4.+0.j 5.+0.j 6.+0.j]]


In [47]:
print(A.T)
print(A.I) 

[[0.72449333 0.0629135 ]
 [0.13697844 0.93928217]]
[[ 1.39797874 -0.20387158]
 [-0.09363718  1.0782982 ]]


In [49]:
linalg.inv(A)
M = np.array([[-1,3,2],[0,-2,1],[1,5,-2]])
M_lower = np.tril(M)
print(M_lower) 

[[-1  0  0]
 [ 0 -2  0]
 [ 1  5 -2]]


In [50]:
M = np.array([[-1,3,2],[0,-2,1],[1,5,-2]])
M_upper = np.triu(M)
print(M_upper)

[[-1  3  2]
 [ 0 -2  1]
 [ 0  0 -2]]


In [52]:
M = np.array([[-1,3,2],[0,-
2,1],[1,5,-2]])
v_diag = np.diag(M) #vector đường chéo
print (v_diag)
M_diag = np.diag(v_diag)
print (M_diag)

[-1 -2 -2]
[[-1  0  0]
 [ 0 -2  0]
 [ 0  0 -2]]


**Bài 3**

In [64]:
import sympy as sp
x = sp.Symbol("x")
y = sp.Symbol("y")
z = sp.Symbol("z")
sp.solve([x*x+2-6, y-1-6, x+z-1, 2*x*x-8, z*z+4-5, y-z-8], [x,y,z])

[(2, 7, -1)]

**Bài 4**

In [65]:
import numpy as np
A = np.array( [ [1,1], [1,0] ] )
b = np.array([1, 0])
n = 10 
for i in range(n):
 b = A.dot(b)
 print(b)

[1 1]
[2 1]
[3 2]
[5 3]
[8 5]
[13  8]
[21 13]
[34 21]
[55 34]
[89 55]


**5.2. Bài toán ứng dụng 3 – Đếm số lượng xe vào khu vực trung tâm **

In [66]:
import sympy as sp
from sympy import Symbol
x1 = Symbol('x1')
x2 = Symbol('x2')
x3 = Symbol('x3')
x4 = Symbol('x4')
from sympy import solve
pt1 = x4+610-450-x1
pt2 = x1+400-x2-640
pt3 = x2+600-x3
pt4 = x3-x4-520
nghiem = sp.solve((pt1, pt2, pt3, pt4))
print(nghiem) 

{x1: x4 + 160, x2: x4 - 80, x3: x4 + 520}
